/* Creacion de Tabla Tutor */
CREATE TABLE TUTOR (
	ID_TUTOR		INT		AUTO_INCREMENT PRIMARY KEY,
   USER_TUTOR           VARCHAR(25) GENERATED ALWAYS AS (CONCAT(NOMBRE_TUTOR, APELLIDO_TUTOR)) STORED,
   NOMBRE_TUTOR         CHAR(20)             NOT NULL,
   APELLIDO_TUTOR       CHAR(20)             NOT NULL,
   PASSWORD_TUTOR_ANIMAL CHAR(20)             NOT NULL,
   PASSWORD_TUTOR_COLOR CHAR(20)             NOT NULL,
   PASSWORD_TUTOR_ACCION CHAR(20)             NOT NULL
);

/* Creacion de Tabla Estudiante */
CREATE TABLE ESTUDIANTE (
	ID_ESTUDIANTE		INT		AUTO_INCREMENT PRIMARY KEY,
  USER_ESTUDIANTE      char(25)      GENERATED ALWAYS AS (CONCAT(NOMBRE_ESTUDIANTE, APELLIDO_ESTUDIANTE)) STORED,
   ID_TUTOR           int            null,
   NOMBRE_ESTUDIANTE    char(20)             not null,
   APELLIDO_ESTUDIANTE  char(20)             not null,
   PASSWORD_ESTUDIANTE_ANIMAL char(20)             not null,
   PASSWORD_ESTUDIANTE_COLOR char(20)             not null,
   PASSWORD_ESTUDIANTE_ACCION char(20)             not null,
   USUARIO_VALIDADO BOOLEAN DEFAULT false  not null,
      constraint FK_ESTUDIAN_TIENE_TUTOR FOREIGN KEY (ID_TUTOR) REFERENCES TUTOR(ID_TUTOR)
ON DELETE CASCADE
);

-- Creación de la Tabla Preguntas de Seguridad
CREATE TABLE PREGUNTAS_SEGURIDAD_ESTUDIANTE (
   ID_ESTUDIANTE         INT PRIMARY KEY,
   PRIMERA_MASCOTA       CHAR(50) NOT NULL,
   CIUDAD_NACIMIENTO     CHAR(50) NOT NULL,
   SEGUNDO_NOMBRE_MAMA   CHAR(50) NOT NULL,
   CONSTRAINT FK_PREGUNTAS_ESTUDIANTE FOREIGN KEY (ID_ESTUDIANTE) REFERENCES ESTUDIANTE(ID_ESTUDIANTE) ON DELETE CASCADE
);

/* Creación de la Tabla LECTURA */
CREATE TABLE LECTURA (
   ID_LECTURA         INT AUTO_INCREMENT PRIMARY KEY,
   NOMBRE_LECTURA     CHAR(50) NOT NULL,
   ID_ESTUDIANTE      INT NOT NULL,
   TIPO_JUEGO         CHAR(50) NOT NULL,
   NOMBRE_INSIGNIA    CHAR(50) GENERATED ALWAYS AS (NOMBRE_LECTURA) STORED,
   INSIGNIA_OBTENIDA  BOOLEAN NOT NULL,
   CONSTRAINT FK_ESTUDIANTE_TIENE_LECTURA FOREIGN KEY (ID_ESTUDIANTE) REFERENCES ESTUDIANTE(ID_ESTUDIANTE)
     ON DELETE CASCADE
);


-- Creación de la tabla PREGUNTA
CREATE TABLE PREGUNTA (
   ID_PREGUNTA          INT AUTO_INCREMENT PRIMARY KEY,
   ID_LECTURA           INT NOT NULL,
   PREGUNTAS_CONTESTADAS INT NOT NULL,
   PREGUNTAS_CORRECTAS  INT NOT NULL,
   HORA_INICIO          TIME,
   HORA_FIN             TIME,
   DURACION             INT AS (TIME_TO_SEC(TIMEDIFF(HORA_FIN, HORA_INICIO)) / 60), -- Columna calculada
   CONSTRAINT FK_PREGUNTA_LECTURA FOREIGN KEY (ID_LECTURA) REFERENCES LECTURA(ID_LECTURA) ON DELETE CASCADE
);


select * from TUTOR;
select * from ESTUDIANTE;
select * from LECTURA;
select * from PREGUNTA; 
select * from PREGUNTAS_SEGURIDAD_ESTUDIANTE;