INSERT INTO TUTOR (NOMBRE_TUTOR, APELLIDO_TUTOR, PASSWORD_TUTOR_ANIMAL, PASSWORD_TUTOR_COLOR, PASSWORD_TUTOR_ACCION)
VALUES ('root', 'root', 'Cuy', 'Amarillo', 'Dormir');

INSERT INTO ESTUDIANTE (ID_TUTOR, NOMBRE_ESTUDIANTE, APELLIDO_ESTUDIANTE, PASSWORD_ESTUDIANTE_ANIMAL, PASSWORD_ESTUDIANTE_COLOR, PASSWORD_ESTUDIANTE_ACCION, USUARIO_VALIDADO)
VALUES (1, 'invitado', 'invitado', 'Cuy', 'Amarillo', 'Dormir', true);